const commerceOptions = [
    { label: "Commerce", value: "Autre", color: "#374151" },
    { label: "Carrefour", value: "Carrefour", color: "#0078C1" },
    { label: "Delhaize", value: "Delhaize", color: "#D71920" },
    { label: "Colruyt", value: "Colruyt", color: "#FF5E00" },
    { label: "Lidl", value: "Lidl", color: "#FFD500" },
    { label: "Aldi", value: "Aldi", color: "#0039A6" },
    { label: "Intermarché", value: "Intermarché", color: "#E60000" },
    { label: "Match", value: "Match", color: "#006837" },
    { label: "Cora", value: "Cora", color: "#005BAC" },
    { label: "Okay", value: "Okay", color: "#0082C8" },
    { label: "Makro", value: "Makro", color: "#F39200" },
    { label: "Bio-Planet", value: "Bio-Planet", color: "#006D5B" },
    { label: "Brico", value: "Brico", color: "#FFD700" },
    { label: "Brico Plan-It", value: "Brico Plan-It", color: "#F7A900" },
    { label: "Hubo", value: "Hubo", color: "#0057B8" },
    { label: "Fast-food", value: "Fast-food", color: "#FF4500" },
    { label: "MisterCash", value: "MisterCash", color: "#0033CC" },
    { label: "Action", value: "Action", color: "#0066CC" },
    { label: "Steam", value: "Steam", color: "#1B2838" },
    { label: "Amazon", value: "Amazon", color: "#FF9900" },
    { label: "Zalando", value: "Zalando", color: "#FF6800" },
    { label: "PayPal", value: "PayPal", color: "#009CDE" },
    { label: "Distributeur", value: "Distributeur", color: "#6C757D" },
    { label: "Restaurant", value: "Restaurant", color: "#E63946" },
    { label: "Gamma", value: "Gamma", color: "#005BAC" },
    { label: "Shop", value: "Shop", color: "#008000" },
    { label: "Banque", value: "Banque", color: "#2D3748" },
    { label: "Mr. Bricolage", value: "Mr. Bricolage", color: "#00A859" },
    { label: "MediaMarkt", value: "MediaMarkt", color: "#D80027" },
    { label: "Krëfel", value: "Krëfel", color: "#0091DA" },
    { label: "Vanden Borre", value: "Vanden Borre", color: "#800000" },
    { label: "Exellent", value: "Exellent", color: "#FFD700" },
    { label: "Selexion", value: "Selexion", color: "#1E90FF" },
    { label: "Decathlon", value: "Decathlon", color: "#0066CC" },
    { label: "Intersport", value: "Intersport", color: "#E63946" },
    { label: "AS Adventure", value: "AS Adventure", color: "#A67C00" },
    { label: "SportsDirect", value: "SportsDirect", color: "#0033A0" },
    { label: "Ikea", value: "Ikea", color: "#0055A4" },
    { label: "Leen Bakker", value: "Leen Bakker", color: "#FF66B2" },
    { label: "Jysk", value: "Jysk", color: "#004B87" },
    { label: "Casa", value: "Casa", color: "#6AB04C" },
    { label: "Hema", value: "Hema", color: "#FF0000" },
    { label: "Dreamland", value: "Dreamland", color: "#0097CE" },
    { label: "Maxi Toys", value: "Maxi Toys", color: "#FFCC00" },
    { label: "Fun", value: "Fun", color: "#F28500" },
    { label: "H&M", value: "H&M", color: "#D91828" },
    { label: "Zara", value: "Zara", color: "#2C2C2C" },
    { label: "C&A", value: "C&A", color: "#003DA5" },
    { label: "Primark", value: "Primark", color: "#0076C8" },
    { label: "Esprit", value: "Esprit", color: "#C41E3A" },
    { label: "JBC", value: "JBC", color: "#FFCC00" },
    { label: "E5 Mode", value: "E5 Mode", color: "#8A2BE2" }
];

export default commerceOptions;
