const commerceOptions = [
    { label: "Commerce", value: "Autre" },
    { label: "Carrefour", value: "Carrefour" },
    { label: "Delhaize", value: "Delhaize" },
    { label: "Colruyt", value: "Colruyt" },
    { label: "Lidl", value: "Lidl" },
    { label: "Aldi", value: "Aldi" },
    { label: "Intermarché", value: "Intermarché" },
    { label: "Match", value: "Match" },
    { label: "Cora", value: "Cora" },
    { label: "Okay", value: "Okay" },
    { label: "Makro", value: "Makro" },
    { label: "Bio-Planet", value: "Bio-Planet" },
    { label: "Brico", value: "Brico" },
    { label: "Brico Plan-It", value: "Brico Plan-It" },
    { label: "Hubo", value: "Hubo" },

    { label: "Fast-food", value: "Fast-food" },
    { label: "MisterCash", value: "MisterCash" },
    { label: "Action", value: "Action" },
    { label: "Steam", value: "Steam" },
    { label: "Amazon", value: "Amazon" },
    { label: "Zalando", value: "Zalando" },
    { label: "PayPal", value: "PayPal" },
    { label: "Distributeur", value: "Distributeur" },
    { label: "Restaurant", value: "Restaurant" },
    { label: "Hubo", value: "Hubo" } ,


    { label: "Gamma", value: "Gamma" },
    { label: "Shop", value: "Shop" },
    { label: "Banque", value: "Banque" },
    { label: "Mr. Bricolage", value: "Mr. Bricolage" },
    { label: "MediaMarkt", value: "MediaMarkt" },
    { label: "Krëfel", value: "Krëfel" },
    { label: "Vanden Borre", value: "Vanden Borre" },
    { label: "Exellent", value: "Exellent" },
    { label: "Selexion", value: "Selexion" },
    { label: "Decathlon", value: "Decathlon" },
    { label: "Intersport", value: "Intersport" },
    { label: "AS Adventure", value: "AS Adventure" },
    { label: "SportsDirect", value: "SportsDirect" },
    { label: "Ikea", value: "Ikea" },
    { label: "Leen Bakker", value: "Leen Bakker" },
    { label: "Jysk", value: "Jysk" },
    { label: "Casa", value: "Casa" },
    { label: "Hema", value: "Hema" },
    { label: "Dreamland", value: "Dreamland" },
    { label: "Maxi Toys", value: "Maxi Toys" },
    { label: "Fun", value: "Fun" },
    { label: "H&M", value: "H&M" },
    { label: "Zara", value: "Zara" },
    { label: "C&A", value: "C&A" },
    { label: "Primark", value: "Primark" },
    { label: "Esprit", value: "Esprit" },
    { label: "JBC", value: "JBC" },
    { label: "E5 Mode", value: "E5 Mode" }
];

export default commerceOptions;
